version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
    volumes:
      - ./code/:/var/www/html/
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx/

  php-fpm:
    build: ./docker/php/
    container_name: php-fpm
    privileged: true
    ports:
      - 9000:9000
    volumes:
      - ./code:/var/www/html
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php-fpm/:/var/log/php-fpm/
    links:
      - mysql 
      - redis
      - es

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/:/var/lib/mysql/
      - ./logs/mysql/:/var/log/mysql/

    environment:
      - MYSQL_ROOT_PASSWORD="huanhuan0921"

  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes:
      - ./data/redis/:/data/

  es:
    image: elasticsearch:2.4.6
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
